### ISSUE TITLE
Carla failed to start on remote server

### ISSUE THREAD

**Issue by ShangGL123** [OpenDriveLab/ThinkTwice#5]
Run the generate data command on the remote server, and the process will exit directly after displaying the following log：

4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.

**Comment by jiaxiaosong1002** [comment]
@changjiahao 
Thanks for your interestes. Note that *Disabling core dumps.* is not error information, it happens normally.

Remember to kill the CARLA process every time you use the provided script since it would use the same port every time.

Try only run *DISPLAY= bash  $CARLA_ROOT/CarlaUE4.sh')  -opengl -carla-rpc-port=20032 -nosound* to make sure CARLA is installed properly. You should see the teminal hangs at "Disabling core dumps." and one CARLA process takes more than 1GB GPU memory. Remeber to make sure the communication port is not occupied by other process. 

Additionally, you could try with remove *-opengl*.

Also, it might due to the speed of the system is too slow. Try to increase the "wait_time" in [Line 124 leaderboard_evaluator.py](https://github.com/OpenDriveLab/ThinkTwice/blob/main/leaderboard/leaderboard/leaderboard_evaluator.py) to 200 so that the python process would wait longer for CARLA to setup up.

**Comment by ShangGL123** [comment]
Does the 8T data in the data generation section refer to 189K frames only for training or does it include validation set?

**Comment by jiaxiaosong1002** [comment]
Include validation.

BTW, for a new question, we suggest open new issues so that it could be clear and helpful for the community.

**Comment by ShangGL123** [comment]
Thank you for your reply.
